#!/bin/bash
read oldrev newrev refname

echo "$(pwd), $GIT_DIR, $oldrev $newrev $refname"

# Get project name from current directory (without .git)
APP_NAME=$(basename "$PWD")
APP_NAME=${APP_NAME%.git}

echo "Deploying $APP_NAME ..."

# Export environment variables for deployment operation.
# These will be picked up in the sub process invoked by
# git checkout later on.

export GIT_DIR=/home/git/repositories/"$APP_NAME".git

APP_DIR=/opt/node/"$APP_NAME"
export GIT_WORK_TREE="$APP_DIR"/.versions/"$APP_NAME"@"$newrev"

echo "Using Git repo $GIT_DIR"
echo "Using Node app folder $GIT_WORK_TREE"

# Check that we've valid repo location.
if [ ! -d "$GIT_DIR" ]; then
    echo "Error, Git repo not found"
    exit 1
fi

# Node app will live in /opt/node/app-name
# so create if it doesn't exist.
if [ ! -d "$APP_DIR" ]; then
    echo "Warning, app folder not found ... creating"
    mkdir -p "$APP_DIR"/.versions
    chown -R node.node "$APP_DIR"
    chmod -R a+rX "$APP_DIR"
fi

# Create app version dir if it doesn't exist.
if [ ! -d "$GIT_WORK_TREE" ]; then
    mkdir -p "$GIT_WORK_TREE"
fi

# Sync the app location with the latest files in the
# repo via git checkout. Also change ownership of all the
# app files to the node user (we're currently root).
echo "Checkouting app files to $GIT_WORK_TREE ..."
unset GIT_INDEX_FILE
git checkout -f
if [ $? != 0 ]; then
    echo "Error, unable to checkout files"
    exit 1
fi
chmod -R a+rX "$GIT_WORK_TREE"
chown -R node.node "$GIT_WORK_TREE"

echo "Installing dependencies and packaging app ..."
cd "$GIT_WORK_TREE"
su -c 'npm install' node
if [ $? != 0 ]; then
    echo "Error, unable to install dependencies and/or packaging app"
    exit 1
fi

cd -

echo "Updating app target..."
rm "$APP_DIR"/current
ln -s "$GIT_WORK_TREE" "$APP_DIR"/current

echo "Restarting via Monit ..."
sleep 1
monit restart "$APP_NAME"
echo "Deployment complete!"
exit 0
